[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.10"

[[constraint]]
  name = "stackmachine.com/blobstore"
  branch = "master"

[[constraint]]
  name = "goji.io"
  version = "2.0.0"
